version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:9.0.4-jdk-browsers
    steps:
      - checkout
      - run: mkdir test-reports
      - run: mvn test
      - store_test_results:
          path: test-output
